application: bitz-game
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

handlers:
- url: /static
  static_dir: src/static

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.app

builtins:
- deferred: on
